# Generated by Django 3.1.3 on 2020-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20201109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
