# Generated by Django 3.1.3 on 2020-11-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20201110_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
