# Generated by Django 3.1.3 on 2020-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20201110_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pasedStamp',
            field=models.CharField(default='0s', max_length=20),
        ),
    ]
