# Generated by Django 3.1.3 on 2020-11-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_comment_pasedstamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pasedStamp',
            new_name='parsedStamp',
        ),
    ]
