# Generated by Django 3.1.3 on 2020-11-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20201111_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
