# Generated by Django 3.1.3 on 2020-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20201116_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='author',
            field=models.CharField(default='noellehamberis', max_length=255),
            preserve_default=False,
        ),
    ]
