# Generated by Django 3.1.3 on 2020-11-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_link_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='author',
        ),
    ]
